# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginShop
spec:
  enabled: true
  requires: ">=2.26.0"
  pluginClass: run.halo.shop.ShopPlugin
  author:
    name: HF
  logo: logo.png
  displayName: "Halo Shop"
  description: "面向实物商品的社区版商城插件"
  license:
    - name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.html"
