apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-aoset
spec:
  displayName: AOSTE
  author:
    name: cnmbdb
    website: https://github.com/cnmbdb
  description: 自主开发的 Halo 商城主题，支持实物与数字商品、商城首页、订单管理和易支付。
  logo: /themes/theme-aoset/assets/store-logo.svg
  homepage: https://github.com/cnmbdb/halo
  repo: https://github.com/cnmbdb/halo
  issues: https://github.com/cnmbdb/halo/issues
  settingName: "theme-aoset-setting"
  configMapName: "theme-earth-configMap"
  version: 1.18.0
  requires: ">=2.22.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/theme-earth/blob/main/LICENSE"
